name: Create New App

on: 
  workflow_dispatch:
    inputs:
      appName:
        description: 'App Name'
        required: true
      framework:
        description: 'Framework'     
        required: true
        default: 'Next.js' 
        type: choice
        options:
        - Next.js
        - Fastify
        - React.js
      createNewRepo:
        description: 'Create New Repo?'
        required: true 
        type: boolean
      repoName:
        description: 'Your Repo Name (Will created if new repo)'
        type: text
        required: true 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.tags }}"
